### ISSUE TITLE
Download Problem in Windows 10

### ISSUE THREAD

**Issue by csmosley5885** [graphtheorysoftware/GraphTea#37]
Clicking the download button for Windows causes the following message to appear: We're sorry, but something went wrong.

**Comment by azinazadi** [comment]
please try again. there might be a problem with your network

**Comment by csmosley5885** [comment]
I've tried about 50 times, restarted my computer a couple times, and reset the modem a couple times

**Comment by azinazadi** [comment]
It's fixed now dear @csmosley5885 . thx for reporting
