### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by brunocalou** [graphtheorysoftware/GraphTea#42]
I downloaded the  [latest version ](https://github.com/graphtheorysoftware/GraphTea/archive/master.zip), extracted to a directory and run make.sh, but the build failed.

Here is the log -> https://gist.github.com/brunocalou/455404f322d713cb5aaf

I'm using elementary OS 0.3.2 Freya (64-bit)

**Comment by brunocalou** [comment]
I tested for the previous version @b766fcbd171c274e12d303967f0fae1cd7b6678c and it built successfully (with no errors, but with 100 warnings)

**Comment by rostam** [comment]
you are right.
I forgot to push the file NDMetis.
I updated already the git repository.

**Comment by brunocalou** [comment]
Great, it's working now x)
